
development:
  adapter: postgresql
  encoding: unicode
  database: story-rev_development
  pool: 5
  username: story-rev
  password: <%= Rails.configuration.sensitive['db_pass'] %>

production:
  adapter: postgresql
  encoding: unicode
  database: story-rev-demo_production
  pool: 5
  username: story-rev-demo
  password: <%= Rails.configuration.sensitive['db_pass'] %>
