
development:
  adapter: postgresql
  encoding: unicode
  database: <%= Rails.configuration.sensitive['db_name'] %>_development
  host: localhost
  pool: 5
  username: <%= Rails.configuration.sensitive['db_username'] %>
  password: <%= Rails.configuration.sensitive['db_pass'] %>

test: &test
  adapter: postgresql
  encoding: unicode
  database: <%= Rails.configuration.sensitive['db_name'] %>_test
  host: localhost
  pool: 5
  username: <%= Rails.configuration.sensitive['db_username'] %>
  password: <%= Rails.configuration.sensitive['db_pass'] %>

production:
  adapter: postgresql
  encoding: unicode
  database: <%= Rails.configuration.sensitive['db_name'] %>_production
  host: localhost
  pool: 5
  username: <%= Rails.configuration.sensitive['db_username'] %>
  password: <%= Rails.configuration.sensitive['db_pass'] %>

cucumber:
  <<: *test